import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";

import { parse } from "smol-toml";

export interface LocalEnvironmentConfig {
  configPath: string;
  exists: boolean;
}

export interface LocalEnvironmentError {
  error: {
    message: string;
  };
}

export interface LocalEnvironmentSuccess {
  environment: Record<string, unknown>;
}

export interface LocalEnvironmentParseResult {
  type: "success";
  environment: Record<string, unknown>;
}

export interface LocalEnvironmentParseError {
  type: "error";
  error: {
    message: string;
  };
}

export interface LocalEnvironmentEntry extends LocalEnvironmentConfig {
  type: "success" | "error";
  environment?: Record<string, unknown>;
  error?: {
    message: string;
  };
}

const AUTOGENERATED_HEADER = "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY";

export function deriveLocalEnvironmentSettingsPath(root: string): string {
  return join(root, ".codex", "environments", "environment.toml");
}

export async function listLocalEnvironments(
  root: string,
): Promise<{ environments: LocalEnvironmentEntry[] }> {
  const configPath = deriveLocalEnvironmentSettingsPath(root);
  try {
    const raw = await readFile(configPath, "utf8");
    const parsed = parseLocalEnvironmentResult(raw);
    return {
      environments: [buildLocalEnvironmentEntry(configPath, parsed)],
    };
  } catch (error) {
    if (isMissingFileError(error)) {
      return {
        environments: [],
      };
    }

    return {
      environments: [
        {
          configPath,
          exists: true,
          type: "error",
          error: {
            message: normalizeErrorMessage(error),
          },
        },
      ],
    };
  }
}

export async function readLocalEnvironmentConfig(
  configPath: string,
): Promise<LocalEnvironmentConfig> {
  const normalizedPath = normalizeLocalEnvironmentConfigPath(configPath);

  try {
    await readFile(normalizedPath, "utf8");
    return {
      configPath: normalizedPath,
      exists: true,
    };
  } catch (error) {
    if (isMissingFileError(error)) {
      return {
        configPath: normalizedPath,
        exists: false,
      };
    }

    throw error;
  }
}

export async function loadLocalEnvironment(
  configPath: string,
): Promise<{ environment: LocalEnvironmentParseResult | LocalEnvironmentParseError }> {
  const normalizedPath = normalizeLocalEnvironmentConfigPath(configPath);
  const raw = await readFile(normalizedPath, "utf8");
  return {
    environment: parseLocalEnvironmentResult(raw),
  };
}

export async function saveLocalEnvironmentConfig(
  configPath: string,
  raw: string,
): Promise<LocalEnvironmentConfig> {
  const normalizedPath = normalizeLocalEnvironmentConfigPath(configPath);
  const contents = normalizeLocalEnvironmentConfigContents(raw);

  await mkdir(dirname(normalizedPath), { recursive: true });
  await writeFile(normalizedPath, contents, "utf8");

  return {
    configPath: normalizedPath,
    exists: true,
  };
}

export async function deleteLocalEnvironmentConfig(configPath: string): Promise<void> {
  await rm(normalizeLocalEnvironmentConfigPath(configPath), { force: true });
}

function isMissingFileError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}

function isJsonRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function parseLocalEnvironmentResult(
  raw: string,
): LocalEnvironmentParseResult | LocalEnvironmentParseError {
  try {
    return {
      type: "success",
      environment: parseLocalEnvironmentToml(raw),
    };
  } catch (error) {
    return {
      type: "error",
      error: {
        message: normalizeErrorMessage(error),
      },
    };
  }
}

function parseLocalEnvironmentToml(raw: string): Record<string, unknown> {
  const parsed = parse(raw);
  if (!isJsonRecord(parsed)) {
    throw new Error("Local environment TOML must contain a top-level table.");
  }

  return parsed;
}

function buildLocalEnvironmentEntry(
  configPath: string,
  result: LocalEnvironmentParseResult | LocalEnvironmentParseError,
): LocalEnvironmentEntry {
  if (result.type === "success") {
    return {
      configPath,
      exists: true,
      type: "success",
      environment: result.environment,
    };
  }

  return {
    configPath,
    exists: true,
    type: "error",
    error: result.error,
  };
}

function normalizeLocalEnvironmentConfigPath(configPath: string): string {
  const normalizedPath = resolve(configPath);
  const environmentsDirectory = dirname(normalizedPath);
  const codexDirectory = dirname(environmentsDirectory);

  if (
    basename(normalizedPath) !== "environment.toml" ||
    basename(environmentsDirectory) !== "environments" ||
    basename(codexDirectory) !== ".codex"
  ) {
    throw new Error("Invalid local environment config path.");
  }

  return normalizedPath;
}

function normalizeLocalEnvironmentConfigContents(raw: string): string {
  const body = raw
    .replace(/^\uFEFF/, "")
    .replace(/^\s+/, "")
    .trimEnd();
  if (body.startsWith(AUTOGENERATED_HEADER)) {
    return `${body}\n`;
  }

  return `${AUTOGENERATED_HEADER}\n${body}\n`;
}

function normalizeErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
